/** Bundled official restaurant menu nutrition — values from published chain
 * nutrition PDFs / calculators (US). Never invent; only curated verified rows. */

export interface RestaurantFoodRecord {
  id: string;
  restaurant: string;
  menuItem: string;
  /** Aliases for search (lowercased matching). */
  aliases?: string[];
  servingSize: string;
  servingWeightGrams?: number;
  calories: number;
  protein: number;
  carbs: number;
  fat: number;
  saturatedFat?: number;
  fiber?: number;
  sugar?: number;
  sodium?: number;
  source: string;
  dateVerified: string;
}

export const RESTAURANT_FOOD_SOURCE =
  'Official restaurant nutrition PDFs / online calculators (US), curated 2024–2026';

/** ~60 popular items across major US chains with published nutrition. */
export const RESTAURANT_FOODS: RestaurantFoodRecord[] = [
  // —— McDonald's ——
  {
    id: 'mcd-big-mac',
    restaurant: "McDonald's",
    menuItem: 'Big Mac',
    aliases: ['bigmac'],
    servingSize: '1 sandwich',
    servingWeightGrams: 215,
    calories: 590,
    protein: 25,
    carbs: 46,
    fat: 34,
    saturatedFat: 11,
    sodium: 1050,
    source: "McDonald's USA Nutrition",
    dateVerified: '2025-06-01',
  },
  {
    id: 'mcd-qp-cheese',
    restaurant: "McDonald's",
    menuItem: 'Quarter Pounder with Cheese',
    aliases: ['quarter pounder', 'qp with cheese'],
    servingSize: '1 sandwich',
    servingWeightGrams: 200,
    calories: 520,
    protein: 30,
    carbs: 42,
    fat: 26,
    saturatedFat: 13,
    sodium: 1140,
    source: "McDonald's USA Nutrition",
    dateVerified: '2025-06-01',
  },
  {
    id: 'mcd-mcchicken',
    restaurant: "McDonald's",
    menuItem: 'McChicken',
    servingSize: '1 sandwich',
    servingWeightGrams: 143,
    calories: 400,
    protein: 14,
    carbs: 40,
    fat: 21,
    saturatedFat: 3.5,
    sodium: 560,
    source: "McDonald's USA Nutrition",
    dateVerified: '2025-06-01',
  },
  {
    id: 'mcd-nuggets-6',
    restaurant: "McDonald's",
    menuItem: 'Chicken McNuggets (6 piece)',
    aliases: ['mcnuggets', 'nuggets 6'],
    servingSize: '6 pieces',
    servingWeightGrams: 96,
    calories: 250,
    protein: 14,
    carbs: 15,
    fat: 15,
    saturatedFat: 2.5,
    sodium: 500,
    source: "McDonald's USA Nutrition",
    dateVerified: '2025-06-01',
  },
  {
    id: 'mcd-fries-med',
    restaurant: "McDonald's",
    menuItem: 'French Fries (Medium)',
    aliases: ['medium fries', 'fries'],
    servingSize: '1 medium',
    servingWeightGrams: 111,
    calories: 320,
    protein: 5,
    carbs: 43,
    fat: 15,
    saturatedFat: 2,
    sodium: 260,
    source: "McDonald's USA Nutrition",
    dateVerified: '2025-06-01',
  },
  {
    id: 'mcd-egg-mcmuffin',
    restaurant: "McDonald's",
    menuItem: 'Egg McMuffin',
    servingSize: '1 sandwich',
    servingWeightGrams: 126,
    calories: 310,
    protein: 17,
    carbs: 30,
    fat: 13,
    saturatedFat: 5,
    sodium: 820,
    source: "McDonald's USA Nutrition",
    dateVerified: '2025-06-01',
  },
  {
    id: 'mcd-filet-o-fish',
    restaurant: "McDonald's",
    menuItem: 'Filet-O-Fish',
    aliases: ['filet o fish'],
    servingSize: '1 sandwich',
    servingWeightGrams: 142,
    calories: 390,
    protein: 16,
    carbs: 39,
    fat: 19,
    saturatedFat: 4,
    sodium: 580,
    source: "McDonald's USA Nutrition",
    dateVerified: '2025-06-01',
  },
  {
    id: 'mcd-apple-pie',
    restaurant: "McDonald's",
    menuItem: 'Baked Apple Pie',
    aliases: ['apple pie'],
    servingSize: '1 pie',
    servingWeightGrams: 77,
    calories: 230,
    protein: 2,
    carbs: 33,
    fat: 11,
    saturatedFat: 5,
    sodium: 100,
    sugar: 14,
    source: "McDonald's USA Nutrition",
    dateVerified: '2025-06-01',
  },
  {
    id: 'mcd-sausage-biscuit',
    restaurant: "McDonald's",
    menuItem: 'Sausage Biscuit',
    servingSize: '1 biscuit',
    servingWeightGrams: 117,
    calories: 460,
    protein: 11,
    carbs: 34,
    fat: 31,
    saturatedFat: 13,
    sodium: 990,
    source: "McDonald's USA Nutrition",
    dateVerified: '2025-06-01',
  },

  // —— Chipotle ——
  {
    id: 'cm-chicken',
    restaurant: 'Chipotle',
    menuItem: 'Chicken',
    aliases: ['chipotle chicken'],
    servingSize: '4 oz serving',
    servingWeightGrams: 113,
    calories: 180,
    protein: 32,
    carbs: 0,
    fat: 7,
    saturatedFat: 2,
    sodium: 310,
    source: 'Chipotle Nutrition Calculator',
    dateVerified: '2025-06-01',
  },
  {
    id: 'cm-steak',
    restaurant: 'Chipotle',
    menuItem: 'Steak',
    aliases: ['chipotle steak'],
    servingSize: '4 oz serving',
    servingWeightGrams: 113,
    calories: 150,
    protein: 21,
    carbs: 1,
    fat: 6,
    saturatedFat: 2.5,
    sodium: 330,
    source: 'Chipotle Nutrition Calculator',
    dateVerified: '2025-06-01',
  },
  {
    id: 'cm-carnitas',
    restaurant: 'Chipotle',
    menuItem: 'Carnitas',
    servingSize: '4 oz serving',
    servingWeightGrams: 113,
    calories: 210,
    protein: 23,
    carbs: 0,
    fat: 12,
    saturatedFat: 4.5,
    sodium: 460,
    source: 'Chipotle Nutrition Calculator',
    dateVerified: '2025-06-01',
  },
  {
    id: 'cm-sofritas',
    restaurant: 'Chipotle',
    menuItem: 'Sofritas',
    servingSize: '4 oz serving',
    servingWeightGrams: 113,
    calories: 150,
    protein: 8,
    carbs: 9,
    fat: 10,
    saturatedFat: 1.5,
    sodium: 560,
    source: 'Chipotle Nutrition Calculator',
    dateVerified: '2025-06-01',
  },
  {
    id: 'cm-white-rice',
    restaurant: 'Chipotle',
    menuItem: 'Cilantro-Lime White Rice',
    aliases: ['white rice', 'chipotle rice'],
    servingSize: '4 oz serving',
    servingWeightGrams: 113,
    calories: 210,
    protein: 4,
    carbs: 40,
    fat: 4,
    saturatedFat: 0.5,
    sodium: 350,
    source: 'Chipotle Nutrition Calculator',
    dateVerified: '2025-06-01',
  },
  {
    id: 'cm-brown-rice',
    restaurant: 'Chipotle',
    menuItem: 'Cilantro-Lime Brown Rice',
    aliases: ['brown rice'],
    servingSize: '4 oz serving',
    servingWeightGrams: 113,
    calories: 210,
    protein: 4,
    carbs: 36,
    fat: 6,
    saturatedFat: 1,
    sodium: 190,
    fiber: 2,
    source: 'Chipotle Nutrition Calculator',
    dateVerified: '2025-06-01',
  },
  {
    id: 'cm-black-beans',
    restaurant: 'Chipotle',
    menuItem: 'Black Beans',
    servingSize: '4 oz serving',
    servingWeightGrams: 113,
    calories: 130,
    protein: 8,
    carbs: 22,
    fat: 1.5,
    saturatedFat: 0,
    sodium: 210,
    fiber: 7,
    source: 'Chipotle Nutrition Calculator',
    dateVerified: '2025-06-01',
  },
  {
    id: 'cm-pinto-beans',
    restaurant: 'Chipotle',
    menuItem: 'Pinto Beans',
    servingSize: '4 oz serving',
    servingWeightGrams: 113,
    calories: 130,
    protein: 8,
    carbs: 21,
    fat: 1.5,
    sodium: 210,
    fiber: 7,
    source: 'Chipotle Nutrition Calculator',
    dateVerified: '2025-06-01',
  },
  {
    id: 'cm-guac',
    restaurant: 'Chipotle',
    menuItem: 'Guacamole',
    aliases: ['guac'],
    servingSize: '4 oz serving',
    servingWeightGrams: 113,
    calories: 230,
    protein: 2,
    carbs: 8,
    fat: 22,
    saturatedFat: 3.5,
    sodium: 370,
    fiber: 6,
    source: 'Chipotle Nutrition Calculator',
    dateVerified: '2025-06-01',
  },
  {
    id: 'cm-cheese',
    restaurant: 'Chipotle',
    menuItem: 'Cheese',
    aliases: ['chipotle cheese'],
    servingSize: '1 oz serving',
    servingWeightGrams: 28,
    calories: 110,
    protein: 6,
    carbs: 1,
    fat: 8,
    saturatedFat: 5,
    sodium: 190,
    source: 'Chipotle Nutrition Calculator',
    dateVerified: '2025-06-01',
  },
  {
    id: 'cm-sour-cream',
    restaurant: 'Chipotle',
    menuItem: 'Sour Cream',
    servingSize: '2 oz serving',
    servingWeightGrams: 57,
    calories: 110,
    protein: 2,
    carbs: 2,
    fat: 9,
    saturatedFat: 6,
    sodium: 30,
    source: 'Chipotle Nutrition Calculator',
    dateVerified: '2025-06-01',
  },
  {
    id: 'cm-fajita',
    restaurant: 'Chipotle',
    menuItem: 'Fajita Vegetables',
    aliases: ['fajita veggies'],
    servingSize: '2.5 oz serving',
    servingWeightGrams: 71,
    calories: 20,
    protein: 1,
    carbs: 5,
    fat: 0,
    sodium: 160,
    source: 'Chipotle Nutrition Calculator',
    dateVerified: '2025-06-01',
  },
  {
    id: 'cm-flour-tortilla',
    restaurant: 'Chipotle',
    menuItem: 'Flour Tortilla (Burrito)',
    aliases: ['burrito tortilla'],
    servingSize: '1 tortilla',
    servingWeightGrams: 104,
    calories: 320,
    protein: 8,
    carbs: 50,
    fat: 9,
    saturatedFat: 3.5,
    sodium: 610,
    source: 'Chipotle Nutrition Calculator',
    dateVerified: '2025-06-01',
  },
  {
    id: 'cm-burrito-bowl-base',
    restaurant: 'Chipotle',
    menuItem: 'Chicken Burrito Bowl (chicken, white rice, black beans, lettuce)',
    aliases: ['chicken bowl', 'burrito bowl', 'chipotle bowl'],
    servingSize: '1 bowl',
    servingWeightGrams: 450,
    calories: 535,
    protein: 45,
    carbs: 64,
    fat: 12.5,
    sodium: 880,
    source: 'Chipotle Nutrition Calculator (component sum)',
    dateVerified: '2025-06-01',
  },

  // —— Starbucks ——
  {
    id: 'sbux-pike-grande',
    restaurant: 'Starbucks',
    menuItem: 'Pike Place Roast (Grande)',
    aliases: ['pike place', 'coffee grande'],
    servingSize: '16 fl oz',
    servingWeightGrams: 473,
    calories: 5,
    protein: 1,
    carbs: 0,
    fat: 0,
    sodium: 10,
    source: 'Starbucks Nutrition',
    dateVerified: '2025-06-01',
  },
  {
    id: 'sbux-latte-grande',
    restaurant: 'Starbucks',
    menuItem: 'Caffè Latte (Grande, 2% milk)',
    aliases: ['latte', 'caffe latte'],
    servingSize: '16 fl oz',
    servingWeightGrams: 480,
    calories: 190,
    protein: 13,
    carbs: 18,
    fat: 7,
    saturatedFat: 4.5,
    sodium: 170,
    sugar: 18,
    source: 'Starbucks Nutrition',
    dateVerified: '2025-06-01',
  },
  {
    id: 'sbux-capp-grande',
    restaurant: 'Starbucks',
    menuItem: 'Cappuccino (Grande, 2% milk)',
    aliases: ['cappuccino'],
    servingSize: '16 fl oz',
    calories: 120,
    protein: 8,
    carbs: 12,
    fat: 4,
    saturatedFat: 2.5,
    sodium: 100,
    source: 'Starbucks Nutrition',
    dateVerified: '2025-06-01',
  },
  {
    id: 'sbux-americano-grande',
    restaurant: 'Starbucks',
    menuItem: 'Caffè Americano (Grande)',
    aliases: ['americano'],
    servingSize: '16 fl oz',
    calories: 15,
    protein: 1,
    carbs: 2,
    fat: 0,
    sodium: 10,
    source: 'Starbucks Nutrition',
    dateVerified: '2025-06-01',
  },
  {
    id: 'sbux-psl-grande',
    restaurant: 'Starbucks',
    menuItem: 'Pumpkin Spice Latte (Grande, 2%, with whip)',
    aliases: ['psl', 'pumpkin spice latte'],
    servingSize: '16 fl oz',
    calories: 390,
    protein: 14,
    carbs: 50,
    fat: 14,
    saturatedFat: 9,
    sodium: 230,
    sugar: 50,
    source: 'Starbucks Nutrition',
    dateVerified: '2025-06-01',
  },
  {
    id: 'sbux-bacon-gouda',
    restaurant: 'Starbucks',
    menuItem: 'Bacon, Gouda & Egg Sandwich',
    aliases: ['bacon gouda'],
    servingSize: '1 sandwich',
    servingWeightGrams: 144,
    calories: 360,
    protein: 17,
    carbs: 35,
    fat: 18,
    saturatedFat: 7,
    sodium: 720,
    source: 'Starbucks Nutrition',
    dateVerified: '2025-06-01',
  },
  {
    id: 'sbux-spinach-feta',
    restaurant: 'Starbucks',
    menuItem: 'Spinach, Feta & Egg White Wrap',
    aliases: ['spinach feta wrap'],
    servingSize: '1 wrap',
    servingWeightGrams: 150,
    calories: 290,
    protein: 19,
    carbs: 33,
    fat: 8,
    saturatedFat: 3.5,
    sodium: 830,
    source: 'Starbucks Nutrition',
    dateVerified: '2025-06-01',
  },
  {
    id: 'sbux-cold-brew-grande',
    restaurant: 'Starbucks',
    menuItem: 'Cold Brew (Grande)',
    aliases: ['cold brew'],
    servingSize: '16 fl oz',
    calories: 5,
    protein: 0,
    carbs: 0,
    fat: 0,
    sodium: 10,
    source: 'Starbucks Nutrition',
    dateVerified: '2025-06-01',
  },

  // —— Subway ——
  {
    id: 'sub-turkey-6',
    restaurant: 'Subway',
    menuItem: 'Turkey Breast Sandwich (6", 9-Grain Wheat)',
    aliases: ['turkey sub', 'turkey breast'],
    servingSize: '6 inch sandwich',
    servingWeightGrams: 219,
    calories: 280,
    protein: 18,
    carbs: 46,
    fat: 3.5,
    saturatedFat: 1,
    sodium: 760,
    source: 'Subway Nutrition',
    dateVerified: '2025-06-01',
  },
  {
    id: 'sub-bmt-6',
    restaurant: 'Subway',
    menuItem: 'Italian B.M.T. (6", 9-Grain Wheat)',
    aliases: ['italian bmt', 'bmt'],
    servingSize: '6 inch sandwich',
    servingWeightGrams: 241,
    calories: 410,
    protein: 20,
    carbs: 46,
    fat: 16,
    saturatedFat: 6,
    sodium: 1270,
    source: 'Subway Nutrition',
    dateVerified: '2025-06-01',
  },
  {
    id: 'sub-teriyaki-6',
    restaurant: 'Subway',
    menuItem: 'Sweet Onion Chicken Teriyaki (6", 9-Grain Wheat)',
    aliases: ['chicken teriyaki', 'teriyaki sub'],
    servingSize: '6 inch sandwich',
    calories: 370,
    protein: 26,
    carbs: 59,
    fat: 4.5,
    saturatedFat: 1,
    sodium: 980,
    source: 'Subway Nutrition',
    dateVerified: '2025-06-01',
  },
  {
    id: 'sub-oven-chicken-6',
    restaurant: 'Subway',
    menuItem: 'Oven Roasted Chicken (6", 9-Grain Wheat)',
    aliases: ['oven roasted chicken'],
    servingSize: '6 inch sandwich',
    calories: 320,
    protein: 23,
    carbs: 47,
    fat: 5,
    saturatedFat: 1.5,
    sodium: 610,
    source: 'Subway Nutrition',
    dateVerified: '2025-06-01',
  },
  {
    id: 'sub-tuna-6',
    restaurant: 'Subway',
    menuItem: 'Tuna Sandwich (6", 9-Grain Wheat)',
    aliases: ['tuna sub'],
    servingSize: '6 inch sandwich',
    calories: 480,
    protein: 20,
    carbs: 45,
    fat: 25,
    saturatedFat: 4.5,
    sodium: 620,
    source: 'Subway Nutrition',
    dateVerified: '2025-06-01',
  },

  // —— Chick-fil-A ——
  {
    id: 'cfa-sandwich',
    restaurant: 'Chick-fil-A',
    menuItem: 'Chicken Sandwich',
    aliases: ['cfa sandwich', 'chick fil a sandwich'],
    servingSize: '1 sandwich',
    servingWeightGrams: 193,
    calories: 440,
    protein: 28,
    carbs: 41,
    fat: 18,
    saturatedFat: 4,
    sodium: 1400,
    source: 'Chick-fil-A Nutrition',
    dateVerified: '2025-06-01',
  },
  {
    id: 'cfa-grilled-sandwich',
    restaurant: 'Chick-fil-A',
    menuItem: 'Grilled Chicken Sandwich',
    aliases: ['grilled sandwich'],
    servingSize: '1 sandwich',
    servingWeightGrams: 224,
    calories: 390,
    protein: 28,
    carbs: 44,
    fat: 12,
    saturatedFat: 2,
    sodium: 990,
    source: 'Chick-fil-A Nutrition',
    dateVerified: '2025-06-01',
  },
  {
    id: 'cfa-nuggets-8',
    restaurant: 'Chick-fil-A',
    menuItem: 'Nuggets (8 count)',
    aliases: ['cfa nuggets', 'chick-fil-a nuggets'],
    servingSize: '8 nuggets',
    servingWeightGrams: 113,
    calories: 250,
    protein: 27,
    carbs: 11,
    fat: 11,
    saturatedFat: 2.5,
    sodium: 930,
    source: 'Chick-fil-A Nutrition',
    dateVerified: '2025-06-01',
  },
  {
    id: 'cfa-grilled-nuggets-8',
    restaurant: 'Chick-fil-A',
    menuItem: 'Grilled Nuggets (8 count)',
    aliases: ['grilled nuggets'],
    servingSize: '8 nuggets',
    servingWeightGrams: 113,
    calories: 130,
    protein: 25,
    carbs: 1,
    fat: 3,
    saturatedFat: 0.5,
    sodium: 440,
    source: 'Chick-fil-A Nutrition',
    dateVerified: '2025-06-01',
  },
  {
    id: 'cfa-waffle-fries-med',
    restaurant: 'Chick-fil-A',
    menuItem: 'Waffle Potato Fries (Medium)',
    aliases: ['waffle fries', 'cfa fries'],
    servingSize: '1 medium',
    servingWeightGrams: 128,
    calories: 420,
    protein: 5,
    carbs: 47,
    fat: 24,
    saturatedFat: 3.5,
    sodium: 290,
    source: 'Chick-fil-A Nutrition',
    dateVerified: '2025-06-01',
  },
  {
    id: 'cfa-minis',
    restaurant: 'Chick-fil-A',
    menuItem: 'Chick-n-Minis (4 count)',
    aliases: ['chick n minis', 'minis'],
    servingSize: '4 minis',
    calories: 360,
    protein: 19,
    carbs: 41,
    fat: 13,
    saturatedFat: 4,
    sodium: 910,
    source: 'Chick-fil-A Nutrition',
    dateVerified: '2025-06-01',
  },
  {
    id: 'cfa-cobb',
    restaurant: 'Chick-fil-A',
    menuItem: 'Cobb Salad (no dressing)',
    aliases: ['cfa cobb'],
    servingSize: '1 salad',
    calories: 430,
    protein: 40,
    carbs: 22,
    fat: 21,
    saturatedFat: 8,
    sodium: 1180,
    source: 'Chick-fil-A Nutrition',
    dateVerified: '2025-06-01',
  },

  // —— Taco Bell ——
  {
    id: 'tb-crunchy-taco',
    restaurant: 'Taco Bell',
    menuItem: 'Crunchy Taco',
    aliases: ['hard taco'],
    servingSize: '1 taco',
    servingWeightGrams: 78,
    calories: 170,
    protein: 8,
    carbs: 13,
    fat: 9,
    saturatedFat: 3.5,
    sodium: 310,
    source: 'Taco Bell Nutrition',
    dateVerified: '2025-06-01',
  },
  {
    id: 'tb-soft-taco',
    restaurant: 'Taco Bell',
    menuItem: 'Soft Taco (Beef)',
    aliases: ['soft taco'],
    servingSize: '1 taco',
    servingWeightGrams: 92,
    calories: 180,
    protein: 9,
    carbs: 18,
    fat: 8,
    saturatedFat: 3.5,
    sodium: 500,
    source: 'Taco Bell Nutrition',
    dateVerified: '2025-06-01',
  },
  {
    id: 'tb-bean-burrito',
    restaurant: 'Taco Bell',
    menuItem: 'Bean Burrito',
    servingSize: '1 burrito',
    servingWeightGrams: 198,
    calories: 350,
    protein: 13,
    carbs: 54,
    fat: 9,
    saturatedFat: 3.5,
    sodium: 1050,
    fiber: 9,
    source: 'Taco Bell Nutrition',
    dateVerified: '2025-06-01',
  },
  {
    id: 'tb-chicken-quesadilla',
    restaurant: 'Taco Bell',
    menuItem: 'Chicken Quesadilla',
    aliases: ['quesadilla'],
    servingSize: '1 quesadilla',
    servingWeightGrams: 184,
    calories: 520,
    protein: 27,
    carbs: 38,
    fat: 28,
    saturatedFat: 12,
    sodium: 1250,
    source: 'Taco Bell Nutrition',
    dateVerified: '2025-06-01',
  },
  {
    id: 'tb-crunchwrap',
    restaurant: 'Taco Bell',
    menuItem: 'Crunchwrap Supreme',
    aliases: ['crunchwrap'],
    servingSize: '1 crunchwrap',
    servingWeightGrams: 222,
    calories: 550,
    protein: 16,
    carbs: 71,
    fat: 22,
    saturatedFat: 7,
    sodium: 1210,
    source: 'Taco Bell Nutrition',
    dateVerified: '2025-06-01',
  },
  {
    id: 'tb-doritos-locos',
    restaurant: 'Taco Bell',
    menuItem: 'Nacho Cheese Doritos Locos Tacos',
    aliases: ['doritos locos taco', 'dlt'],
    servingSize: '1 taco',
    servingWeightGrams: 78,
    calories: 170,
    protein: 8,
    carbs: 13,
    fat: 9,
    saturatedFat: 3.5,
    sodium: 360,
    source: 'Taco Bell Nutrition',
    dateVerified: '2025-06-01',
  },
  {
    id: 'tb-chalupa',
    restaurant: 'Taco Bell',
    menuItem: 'Chalupa Supreme (Beef)',
    aliases: ['chalupa'],
    servingSize: '1 chalupa',
    calories: 350,
    protein: 12,
    carbs: 29,
    fat: 20,
    saturatedFat: 5,
    sodium: 540,
    source: 'Taco Bell Nutrition',
    dateVerified: '2025-06-01',
  },
  {
    id: 'tb-power-menu-bowl',
    restaurant: 'Taco Bell',
    menuItem: 'Power Menu Bowl (Chicken)',
    aliases: ['power bowl', 'power menu bowl'],
    servingSize: '1 bowl',
    calories: 470,
    protein: 26,
    carbs: 50,
    fat: 19,
    saturatedFat: 5,
    sodium: 1210,
    source: 'Taco Bell Nutrition',
    dateVerified: '2025-06-01',
  },
];
